"""Add new suspect fields

Revision ID: 321229569474
Revises: 
Create Date: 2025-11-07 00:47:25.383979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321229569474'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suspects', sa.Column('vehicle_info', sa.Text(), nullable=True))
    op.add_column('suspects', sa.Column('gang_affiliation', sa.Text(), nullable=True))
    op.add_column('suspects', sa.Column('is_informant', sa.Boolean(), nullable=True))
    op.add_column('suspects', sa.Column('connections', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suspects', 'connections')
    op.drop_column('suspects', 'is_informant')
    op.drop_column('suspects', 'gang_affiliation')
    op.drop_column('suspects', 'vehicle_info')
    # ### end Alembic commands ###